# Generated by Django 2.2.5 on 2019-09-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190913_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readings',
            name='statementMonth',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='readings',
            name='statementYear',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
